### ISSUE TITLE
Open sourcing of dead Alea GPU

### ISSUE THREAD

**Issue by WonkySoft** [quantalea/AleaNotebooks#4]
Its clear from all the dead links on the website and general lack of updates that the Alea gpu project is dead. I tried just building one of the basic examples and that doesn't work because it depends on a version of fsharp.core that isn't available from nuget anymore. So, is there any reason Alea GPU can't be open sourced?

**Comment by degloff** [comment]
Well, the Alea Notebooks are not maintained anymore. But we still continued to support the Enterprise version of Alea GPU.
